# Generated by Django 3.1.6 on 2021-04-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=50)),
                ('isbn', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
